version: '1.0.{build}'
configuration:
- Debug
platform: Any CPU
environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
install:
- rd /s /q "C:\Program Files\dotnet\sdk\1.0.1"
init:
- ps: $Env:LABEL = "beta" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
before_build:
- appveyor-retry dotnet restore -v Minimal
build_script:
- dotnet build "KafkaAvroNet" -c %CONFIGURATION% --no-dependencies 
after_build:
- dotnet pack "KafkaAvroNet" -c %CONFIGURATION% --no-build -o artifacts
artifacts:
- path: artifacts\**\*.*
deploy:
  provider: NuGet
  api_key:
    secure: <<TOBE ADDED>>
  skip_symbols: false
  artifact: /.*\.nupkg/
  on:
    branch: master