version: 1.0.{build}
image: Visual Studio 2017
configuration:
- Debug
platform: Any CPU
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
build_script:
- dotnet build "KafkaAvroNet.sln" -c %CONFIGURATION%
after_build:
- dotnet pack Core/KafkaAvroNet.SchemaRegistry/KafkaAvroNet.SchemaRegistry.csproj -c "Debug" --no-build --output \nupkgs
- dotnet pack Kafka-Net-Manager/KafkaAvroNet/KafkaAvroNet.csproj -c "Debug" --no-build --output \nupkgs 
- dotnet pack Core/KafkaAvroNet.Avro/KafkaAvroNet.Avro.csproj -c "Debug" --no-build --output \nupkgs
- dotnet pack Core/KafkaAvroNet.Kafka/KafkaAvroNet.Kafka.csproj -c "Debug" --no-build --output \nupkgs
test_script:
- ps: ForEach ($folder in (Get-ChildItem -Path test -Directory)) { dotnet test $folder.FullName   -r . --no-build}
deploy:
  provider: NuGet
  api_key:
    secure: <<TOBE ADDED>>
  skip_symbols: false
  artifact: /.*\.nupkg/
  on:
    branch: master